name: Update ICS

on:
  schedule:
    - cron: '0 * * * *'   # every hour (UTC)
  workflow_dispatch:       # allow manual run

jobs:
  download-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download ICS file
        run: |
          curl "http://p135-caldav.icloud.com/published/2/MTE4NDIxNDM0ODExODQyMfCUu7xP-sGAfBxl3uh4ZYGgKw49XDtUNHxNXFfp-n2HUCLrdWc_APvPHxDGM8NvgkrrL3rDMO63Sl45YHepKE8" --output calendar.ics

      - name: Commit and push if changed
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add calendar.ics
          if git diff --cached --quiet; then
            echo "No changes in ICS file"
            exit 0
          fi
          git commit -m "Update ICS file"
          git push
