name: Update PH ICS

on:
  schedule:
    - cron: '0 */12 * * *'   # every 12 hours (UTC)
  workflow_dispatch:       # allow manual run

permissions:
  contents: write  # Add this line

jobs:
  download-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download ICS file
        run: |
          curl -L "https://calendar.google.com/calendar/ical/en.singapore%23holiday%40group.v.calendar.google.com/public/basic.ics" --output basic.ics

      - name: Commit and push if changed
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add basic.ics
          if git diff --cached --quiet; then
            echo "No changes in ICS file"
            exit 0
          fi
          git commit -m "Update ICS file"
          git push